resume/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')), 
    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name='website'

urlpatterns = [
    
   
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('education', education_view, name='education'),
    path('experiences', experiences_view, name='experiences'),
    path('languages', languages_view, name='languages'),
    path('skills', skills_view, name='skills'),
    
   ]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render

# Create your views here.


def index_view(request):
    
     return render(request, 'website/index.html')





cont={'tel':'+971 56 808 7789', 'city':'Dubai, UAE', 'email':'bagheri.payam@gmail.com', 'job':'BI Developer &amp;  SQL Server Expert'} 
def about_view(request):
    
     return render(request, 'website/about.html', cont)
 
 
 
context ={'email':'bagheri.payam@gmail.com', 'tel':'+971 56 808 7789', 'location':'Corniche, Dubai, UAE'}
def contact_view(request):
    
     return render(request, 'website/contact.html', context)
 
def education_view(request):
    
     return render(request, 'website/education.html')
 
def experiences_view(request):
    
     return render(request, 'website/experiences.html')
 
def languages_view(request):
    
     return render(request, 'website/languages.html')
 
def skills_view(request):
    
     return render(request, 'website/skills.html')
 
 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Payam</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Kelly
  * Updated: Jan 29 2024 with Bootstrap v5.3.2
  * Template URL: https://bootstrapmade.com/kelly-free-bootstrap-cv-resume-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container-fluid d-flex justify-content-between align-items-center">

      <h1 class="logo me-auto me-lg-0"><a href="index.html">PAYAM</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="{% static 'img/logo.png' %}" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="active" href="{% url 'website:index' %}">Home</a></li>
          <li><a href={% url 'website:about' %}>About</a></li>
		   <li><a href={% url 'website:skills' %}>Skills</a></li>

          <li><a href={% url 'website:education' %}>Education &amp; Certificates </a></li>
          <li><a href={% url 'website:languages' %}>Languages</a></li>
		            <li><a href={% url 'website:experiences' %}>Experinences</a></li>
          <li><a href={% url 'website:contact' %}>Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      <div class="header-social-links">
        <a href="https://www.linkedin.com/in/bagheripayam/" class="linkedin" target="_blank"><i class="bi bi-linkedin"></i></i></a>
<a href="https://github.com/payam1979" class="github" target="_blank"><i class="bi bi-github"></i></i></a>
<a href="https://join.skype.com/invite/syuU6iA12Phq" class="skype" target="_blank"><i class="bi bi-skype"></i></i></a>
<a href="https://learn.microsoft.com/en-us/users/payambagheri-1444/" class="microsoft" target="_blank"><i class="bi bi-microsoft"></i></i></a>
      </div>

    </div>

  </header><!-- End Header -->
  {% block  content %}
  {% endblock  %}
   <!-- ======= Footer ======= -->
   <footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Payam</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/kelly-free-bootstrap-cv-resume-html-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

templates/website/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>About</h2>
          
        </div>

        <div class="row">
          <div class="col-lg-4">
            <img src="{% static 'img/payam1.jpg' %}" class="img-fluid" alt="">
          </div>
          <div class="col-lg-8 pt-4 pt-lg-0 content">
		      <br>
		  		 
		  
            <h3>{{job}}</h3>
           
            <div class="row">
              <div class="col-lg-6">
                <ul>
                  <li><i class="bi bi-rounded-right"></i> <strong>Birthday:</strong> 25 Jan 1979</li>
                  <!-- <li><i class="bi bi-rounded-right"></i> <strong>Website:</strong> www.payambagheri.com</li> -->
                  <li><i class="bi bi-rounded-right"></i> <strong>Phone:</strong> {{tel}}</li>
                  <li><i class="bi bi-rounded-right"></i> <strong>City:</strong> {{city}}</li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul>
                  <!-- <li><i class="bi bi-rounded-right"></i> <strong>Age:</strong> 45</li> -->
                  <li><i class="bi bi-rounded-right"></i> <strong>Degree:</strong> Materials and Metallurgical Engineering, Bachelor's Degree</li>
                  <li><i class="bi bi-rounded-right"></i> <strong>Email:</strong> {{email}}</li>
                  <!-- <li><i class="bi bi-rounded-right"></i> <strong>Freelance:</strong> Available</li> -->
                </ul>
              </div>
            </div>
            <p> BI Developer with five years of experience in implementing OLTP Databases and Data 
                warehouses, creating ETL packages with Microsoft SSIS, and writing SQL queries to create Report.
                Visualizing data by DAX and Power BI to help make data-driven decisions. I am looking for a position 
                where I can use my proven SQL skills, improve the company's database and develop software to increase 
                productivity. I have started developing and implementing data solutions and have proven experience in 
                improving process quality.
                In the field of programming languages, I first started by learning Java and developed a warehouse-related 
                program. With Java in Android programming, I developed a second version of my warehouse app for 
                Android. For better work with data, I learned Python. I studied HTML, CSS, JavaScript. I became familiar 
                with SAP and ABAP programming language. 
                I have 14 years of experience, working in industrial environments. During these years, I learned the 
                processes of Production, Warehousing, Sales, Quality Assurance, Purchasing, and Planning. I believe my 
                previous experiences have been helping me in the next chapter of my work as a Software programmer.
                I am interested in new challenges and I enjoy solving problems.  
                <a href="https://www.linkedin.com/in/bagheripayam/" class="linkedin" target="_blank"><i class="bi bi-linkedin"></i></i></a>

                <a href="https://github.com/payam1979" class="github" target="_blank"><i class="bi bi-github"></i></i></a>

                <a href="https://join.skype.com/invite/syuU6iA12Phq" class="skype" target="_blank"><i class="bi bi-skype"></i></i></a>

                <a href="https://learn.microsoft.com/en-us/users/payambagheri-1444/" class="microsoft" target="_blank"><i class="bi bi-microsoft"></i></i></a></p>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->

    
  </main><!-- End #main -->

  {% endblock %}

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <main id="main">
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">
        <div class="section-title">
          <h2>Contact</h2>
        </div>

        <div class="row mt-5">
          <div class="col-lg-4">
            <div class="info">
              <div class="address">
                <i class="bi bi-geo-alt"></i>
                <h4>Location:</h4>
                <p>{{location}}</p>
              </div>

              <div class="email">
                <i class="bi bi-envelope"></i>
                <h4>Email:</h4>
                <p>{{email}}</p>
              </div>

              <div class="phone">
                <i class="bi bi-phone"></i>
                <h4>Phone:</h4>
                <p>{{tel}}</p>
              </div>
            </div>
          </div>

          <div class="col-lg-8 mt-5 mt-lg-0">
            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required />
                </div>
                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required />
                </div>
              </div>
              <div class="form-group mt-3">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required />
              </div>
              <div class="form-group mt-3">
                <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
              </div>
              <div class="my-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div>
              <div class="text-center">
                <button type="submit">Send Message</button>
              </div>
            </form>
          </div>
        </div>

        <br />
        <hr />
        <div>
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1072.6086189625548!2d55.300937788727964!3d25.276943550744548!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f431291619193%3A0x17fb026d1e6b8ac8!2sSherina%202%20-%20Sherina%20Plaza!5e0!3m2!1sen!2s!4v1709285740333!5m2!1sen!2s" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
      </div>
    </section>
    <!-- End Contact Section -->
  </main>
  <!-- End #main -->
{% endblock %}

templates/website/experiences.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <main id="main">
    <!-- ======= Resume Section ======= -->
    <section id="resume" class="resume">
      <div class="container" data-aos="fade-up">
        <div class="section-title">
          <h2>Experiences</h2>
        </div>

        <div class="row">
          <div class="col-md-12">
            <h3 class="resume-title">Professional Experience</h3>
            <br />
            <div class="resume-item">
              <h4>BI Developer and SQL Server Expert</h4>

              <p>
                <em>Premium Technical Support (PTS), Dubai, UAE</em>
              </p>
              <h5>2022 - Present</h5>
              <p>
                <h5>Key Responsibilities:</h5>
                <ul>
                  <li>Redesign databases.</li>
                  <li>Design OLTP Data Model and Create SQL Objects, Tables, Procedures, etc.</li>
                  <li>Design ETL packages with SSIS and fill Data in the Data warehouse, Customize DWH Tables.</li>
                  <li>Create business reports with SQL Query and Power BI.</li>
                </ul>

                <h5>Key achivments:</h5>
                <ul>
                  <li>Redesigned databases for better due to making data usable.</li>
                  <li>Created more than 10 reports and dashboards using DAX and Power BI.</li>
                </ul>
              </p>
            </div>
            <hr />
            <div class="resume-item">
              <h4>BI Developer and SQL Server Expert</h4>

              <p>
                <em>Soshiance, Tehran, Iran</em>
              </p>
              <h5>2018 - 2022</h5>
              <p>This Company established in 2003 with the aim of providing products and services in the field of Information and Communication Technology.</p>

              <p>
                <h5>Key Responsibilities:</h5>
                <ul>
                  <li>Work closely with clients, Analyze customer business requirements, gathering and processing.</li>
                  <li>Design OLTP Data Model and Create SQL Objects, Tables, Procedures, etc.</li>
                  <li>Design ETL packages with SSIS and fill Data in the Data warehouse, Customize DWH Tables.</li>
                  <li>Create business reports with SQL Query and Power BI.</li>
                </ul>

                <h5>Key achivments:</h5>
                <ul>
                  <li>Designed 5+ databases for new products (coordinated with the software developer team) due to client’s needs.</li>
                  <li>Converted 20+ reports from other systems into SSRS.</li>
                  <li>Trained 5+ business users in data modeling in Power BI for creating reports.</li>
                  <li>Created 50+ reports using Power BI.</li>
                  <li>Redesigned 5+ older dashboards to improve performance and decrease the time of analysis.</li>
                </ul>
              </p>
            </div>

            <hr />
            <div class="resume-item">
              <h4>Production Line Expert</h4>

              <p>
                <em>Poomar, Markazi, Iran</em>
              </p>
              <h5>2014 - 2018</h5>
              <p>This company founded in 1972 with the aim of manufacturing stationery and office furniture.</p>
              <p>
                <h5>Key Responsibilities:</h5>
                <ul>
                  <li>Analyzing customer requirements, Design and manage each project individually.</li>
                  <li>Device repair and maintenance management.</li>
                  <li>Visiting the installation projects. (Office furniture).</li>
                  <li>Training of construction and installation personnel.</li>
                  <li>Calculate the costs of each project separately and notify the CEO.</li>
                </ul>

                <h5>Key achivments:</h5>
                <ul>
                  <li>Reduced production costs by increasing the productivity of labor.</li>
                  <li>Reduced production waste by reviewing and redesigning products.</li>
                  <li>Reduced product delivery time to the customer with full supervision from design to production and delivery.</li>
                </ul>
              </p>
            </div>
            <hr />
            <div class="resume-item">
              <h4>Product Manager</h4>

              <p>
                <em>FaraNiroo Sazeh, Alborz, Iran</em>
              </p>
              <h5>2006 - 2014</h5>
              <p>This company was founded in 2005 with the aim of manufacturing various types of anchor bolts, patterns, various bolts and nuts (galvanized and phosphate), tray and ladder of cable and other apparatuses as required by industries.</p>
              <p>
                <h5>Key Responsibilities:</h5>
                <ul>
                  <li>Analyzing customer requirements, gathering and managing the whole project.</li>
                  <li>Find or build new technologies for this category.</li>
                  <li>Analysis and review of accounting and warehousing.</li>
                  <li>Recruitment and training of personnel.</li>
                  <li>Prepare and submit reports to the board</li>
                </ul>

                <h5>Key achivments:</h5>
                <ul>
                  <li>Construction of all structures required for power substations up to 400kw capacity.</li>
                  <li>Construction of all required structures for more than 20 electrical substations.(63-230-400).</li>
                </ul>
              </p>
            </div>
            <hr />
            <div class="resume-item">
              <h4>Quality Assurance Manager</h4>

              <p>
                <em>Nasoozmehr, Alborz, Iran</em>
              </p>
              <h5>2004 - 2006</h5>
              <p>This company established in 1998 with the aim of producing industrial parts from alloy steels. Company produces all kinds of low-alloy; high-alloy and non-alloy steel products with the use of experienced and expert workers as well as advanced equipment in compliance with international standards and guarantees the satisfaction of its customers.</p>
              <p>
                <h5>Key Responsibilities:</h5>

                <ul>
                  <li>Design and creation of quality management system.</li>
                  <li>Follow up on quality management system requirements.</li>
                  <li>Audit of quality management system.</li>
                </ul>

                <h5>Key achivments:</h5>
                <ul>
                  <li>We have succeeded in obtaining the ISO 9000 certification.</li>
                </ul>
              </p>
            </div>
            <hr />
          </div>
        </div>
      </div>
    </section>
    <!-- End Resume Section -->
  </main>
  <!-- End #main -->
{% endblock %}

templates/website/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
 

  <!-- ======= Hero Section ======= -->
  <section id="hero"  class="d-flex align-items-center">
    <div class="container d-flex flex-column align-items-center" data-aos="zoom-in" data-aos-delay="100">
	
      <h1>Payam Bagheri</h1>
      <h6>I'm a Business Intelligence Developer and SQL Expert from Iran</h6>
	  <br>
      <a href={% url 'website:about' %} class="btn-about" style="width:180px; text-align:center;">About Me</a>
    </div>
	
  </section><!-- End Hero -->
{% endblock %}

templates/website/languages.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <main id="main">

    <!-- ======= Portfolio Section ======= -->
   
		
		
		
		  <section id="skills" class="skills">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Languages</h2>
        </div>
		<br>
		<br>
		<br>
		<br>

        <div class="row skills-content">

          <div class="col-md-12">
		  
			<div class="progress">
              <span class="skill">Persian(nativ) <i class="val">100%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">English <i class="val">90%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">German <i class="val">70%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>


          </div>

      </div>
	  
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
	  <br>
    </section>

  </main><!-- End #main -->

 {% endblock %}
 

templates/website/skills.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <main id="main">
    <!-- ======= Skills Section ======= -->
    <section id="skills" class="skills">
      <div class="container" data-aos="fade-up">
        <div class="section-title">
          <h2>Skills</h2>
        </div>

        <div class="row skills-content">
          <div class="col-lg-6">
            <div class="progress">
              <span class="skill">python <i class="val">100%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">HTML <i class="val">100%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">CSS <i class="val">100%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">JavaScript <i class="val">100%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">Git <i class="val">100%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="progress">
              <span class="skill">abap <i class="val">80%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">Java <i class="val">90%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">SQL <i class="val">90%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">dax <i class="val">90%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>

            <div class="progress">
              <span class="skill">power bi <i class="val">90%</i></span>
              <div class="progress-bar-wrap">
                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End Skills Section -->
  </main>
  <!-- End #main -->
{% endblock %}